### ISSUE TITLE
Project reorganization

### ISSUE THREAD

**Issue by GoupilDev** [matiboux/matiboux.github.io#1]
Hello !

It's just a simple reorganization of the project with the creation of "assets", "js" and "css" folders. The project will look more clean !

You can look here for the reorganization : https://github.com/DeerisLeGris/matiboux.github.io/commit/a362e82b8cacd5375fd491be43fe34f0376abac3

**Comment by matiboux** [comment]
Nice, thank you for this :3

Please open a pull request for this, I'd be happy to merge your contribution!

**Comment by GoupilDev** [comment]
Done https://github.com/matiboux/matiboux.github.io/pull/2 !
